### ISSUE TITLE
【Bug】从通知点击进入 MainActivity 发生 Crash

### ISSUE THREAD

**Issue by jamweak** [KunMinX/Jetpack-MVVM-Best-Practice#12]
复现方法：MainActivity 在前台，点击播放音乐，下拉通知栏，点击通知进入 MainActivity
出现概率: 100%

Stacktrace：
com.kunminx.puremusic E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.kunminx.puremusic, PID: 2055
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.kunminx.puremusic/com.kunminx.puremusic.MainActivity}: java.lang.IllegalArgumentException: Cannot add the same observer with different lifecycles
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalArgumentException: Cannot add the same observer with different lifecycles
        at androidx.lifecycle.LiveData.observe(LiveData.java:197)
        at com.kunminx.architecture.bridge.callback.UnPeekLiveData.observe(UnPeekLiveData.java:39)
        at com.kunminx.puremusic.ui.base.BaseActivity.onCreate(BaseActivity.java:52)
        at com.kunminx.puremusic.MainActivity.onCreate(MainActivity.java:43)
        at android.app.Activity.performCreate(Activity.java:7801)
        at android.app.Activity.performCreate(Activity.java:7790)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

我认为这里是因为 MainActivity 没有设置启动模式，导致重复初始化了，加上了 SingleTask, SingleTop, SingleInstance 都可以解决此问题，但我隐约觉得这个不是 root cause。

LifeCycle 库用得不多，请大佬给解释一下这个问题。

**Comment by KunMinX** [comment]
@jamweak 
感谢你的测试和反馈！
这个问题是 LiveData “设计如此” 造成的。通过 LiveData 的 observe 方法就能轻松看到对重复添加 同 Observer 但不同 LifeCycleOwner 的抛出异常处理。

为什么 LiveData 这么设计呢？
考虑到 LiveData 需要根据 LifeCycleOwner 的生命周期状态来判断是否给该 Owner 发送数据，因而唯有确保一个 Observer 只对应唯一 一个同名 Owner 实例，才能确保排他性，和状态判断的正确性。

通常 LifeCycle 会在 Owner destory 时自动解绑，从而没有上述问题。
而你遇到的这个问题，是由于 MainActivity 还在可见模式，而 通知栏重新打开了一个 MainActivity，使得同时有两个同名 Owner 试图匹配一个 Observer，从而抛出上述异常。

对此，你给的解决办法是可以的，在单 Activity 架构中，singleTop、singleTask 启动模式都是 ok 的。

**Comment by jamweak** [comment]
@KunMinX 
感谢解惑！
深入思考了一下，MainActivity 中的问题，可以通过设置 lauchMode 来解决，但是在 BaseActivity 中，还有一个 NetworkStateManager.getInstance().mNetworkStateCallback，对于这个的话，似乎要想一下更常规的解决方法了。
为何不把它放到 SharedViewModel 去做全 APP 范围内的监听呢？

**Comment by KunMinX** [comment]
@jamweak 
SharedViewModel 是专职于页面间通信，NetworkStateManager 专职于网络状态管理，被封装在 Activity 基类，使得对开发者隐藏，而避免接触和改动这些内容。

后期我会在 Activity 基类添加一个网络状态空方法钩子，给 Activity 子类实现用。

**Comment by jamweak** [comment]
@KunMinX 
其实我认为监听网络状态的实现使用 LiveData 有些不太合适，如果网络状态足够重要，每个 Activity 页面都需要关注的话，为什么不放到 Application 中直接注册 receiver 呢？这样的话，就不会涉及因子页面的 LifeCycle 变化而频繁 add/remove observer 了。

**Comment by KunMinX** [comment]
@jamweak 
对于网络状态，不同页面会有不同的 UI 逻辑处理，因而通过 liveData 来分发给多个页面来订阅。
而且 liveData 包含生命周期安全的设计，可以避免 Null 安全等问题。

**Comment by KunMinX** [comment]
@jamweak 
找到引发这个现象的根源的根源了，是 lambda 导致。lambda 中不可空实现，否则会被认为是同一个 Observer，
代码已更新，缘由详见：

https://stackoverflow.com/questions/47025233/android-lifecycle-library-cannot-add-the-same-observer-with-different-lifecycle
